### ISSUE TITLE
Add argument to specify TDS version

### ISSUE THREAD

**Issue by Doctor-love** [lausser/check_mssql_health#12]
It would be great if it was possible to specify TDS version with an argument.
I have recently configured monitoring for some MSSQL 2012 servers and it requires TDS version 8.0, so at the moment my only option is to change the version globally or add each server in the FreeTDS configuration file.

Thanks for a great plugin!

**Comment by historicbruno** [comment]
Out of curiosity, what error do you get when you try connecting with an incorrect TDS version? I am having an issue connecting to a MS SQL server without using the server name from freetds.conf (which specifies TDS version 8.0), but the error message is useless.

**Comment by Doctor-love** [comment]
Closing issue as it have gone stale and I no longer have the sever-side available for testing.
