### ISSUE TITLE
databasefree mode breaks on MSSQL DBs with unlimited max size and no permissions for xp_fixeddrives

### ISSUE THREAD

**Issue by historicbruno** [lausser/check_mssql_health#18]
Basically, databasefree mode returns bogus results in this case, because unlimited max size means the check script will default to 4GB, unless xp_fixeddrives can be used, but that seems to require sysadmin permissions or at least more permissions than we have granted the user (this is on a MSSQL 2012 server). Without the permissions, xp_fixeddrives gives no results and the DB drive size is unknown. In that case, unlimited size DBs over 4GB return negative free space, and the other results aren't accurate.

I don't see the value of the 4GB max calculation (maybe a FAT32 relic?), IMO it will almost always be wrong, and it would be better to clearly indicate unknown status to avoid confusion (like if xp_fixeddrives returns no results and the DBs have unlimited space).

**Comment by lausser** [comment]
Permissions for xp_fixeddrives  is a prerequisite.
