### ISSUE TITLE
Missing installation info on Monitoring::GLPlugin

### ISSUE THREAD

**Issue by ronator** [lausser/check_mssql_health#23]
Hi there,
the installation description (https://labs.consol.de/nagios/check_mssql_health/#installation) mentions the Perl module DBD::Sybase but it lacks info regarding your own Perl module:

Can't locate Monitoring/GLPlugin/Commandline/Extraopts.pm in @INC (you may need to install the Monitoring::GLPlugin::Commandline::Extraopts module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /opt/check_mssql_health/libexec/check_mssql_health line 83.

I found it in CPAN:
CPAN_FILE    L/LA/LAUSSER/Monitoring-GLPlugin-2.3.tar.gz

Maybe you want to add this requirement to your description.

**Comment by lausser** [comment]
You don't need the Monitoring-GLPlugin module. It's already included in the check_mssql_health-tgz. I just forgot to add the extraopts file to the packaging list. There is an update 2.6.4.4 which should be complete.

**Comment by ronator** [comment]
Thank you.
