### ISSUE TITLE
DBD:SYBASE Change to BBDD Mysql

### ISSUE THREAD

**Issue by fvera90** [lausser/check_mssql_health#29]
Hello everyone

I find the following problem when I run the plugin from the command line, I return the correct values, when I implement it in my monitoring system "ICINGA2" gives me a problem.

![image](https://cloud.githubusercontent.com/assets/23697090/26558613/7c1ff8de-44aa-11e7-90ca-f497e3125ee2.png)

I understand that you have to create your own DBD: Sybase, but it would be possible to use the data I have hosted in my MySQL database

Thank you, I hope answer

Regards!

**Comment by lausser** [comment]
Sorry, this is a broken Installation of Perl od DBD::Sybase or both. You have to ask the Icinga authors why they are running plugins under a different environment than that you have in your shell.
