### ISSUE TITLE
 Adaptive Server connection failed with V2.6.4.13

### ISSUE THREAD

**Issue by R-Sommer** [lausser/check_mssql_health#33]
CRITICAL - DBI connect(';server=192.168.3.41','nagios',...) failed: Server message number=18456 severity=14 state=1 line=1 server=TEST01 text=Login failed for user 'nagios'. OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (34)
Server 192.168.53.41, database
Message String: Adaptive Server connection failed
 at ./check_mssql_health-2.6.4.13 line 6419.

Running V2.6.4.12 with the same parameters on the same machines works fine.

Target machine:
Microsoft SQL Server 2012 (SP2-GDR) (KB3194719) - 11.0.5388.0 (X64) 
	Sep 23 2016 16:56:29 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

BTW: We are using SQL Server authentication all the time

**Comment by lausser** [comment]
2.6.4.13 had a very silly bug inside.
Since yesterday...
* 2018-03-22 2.6.4.14
  fix a bug in password decoding

**Comment by R-Sommer** [comment]
Yeah, that works. Many thanks especially for that fast fix.
