### ISSUE TITLE
Not working in SQLServer 2016

### ISSUE THREAD

**Issue by dtrinf** [lausser/check_mssql_health#35]
Hi,

I've been trying the plugin with SQLServer 2016 but I've dettected some problems like the above one.
Is the plugin compatible with SQLServer 2016 version?

 /usr/lib64/nagios/plugins/contrib/check_mssql_health-2.6.4.14/libexec/check_mssql_health --server=10.14.0.224 --username=cacti --password=XXXX  --mode full-scans --warning=100 --critical=500 --port=1433 -t 15 --commit
CRITICAL - DBD::Sybase::st DESTROY failed: Server message number=8179 severity=16 state=8 line=1 server=COMPENSA46 text=Could not find prepared statement with handle 0. , unable to aquire counter data SQLServer:Access Methods Full Scans/sec

/usr/lib64/nagios/plugins/contrib/check_mssql_health-2.6.4.14/libexec/check_mssql_health --server=10.14.0.224 --username=cacti --password=XXXXXXX --mode transactions --warning=10000 --critical=50000 --port=1433 -t 10
CRITICAL - DBD::Sybase::st execute failed: Server message number=262 severity=14 state=1 line=2 server=COMPENSA46 text=VIEW DATABASE STATE permission denied in database 'master'. Server message number=297 severity=16 state=1 line=2 server=COMPENSA46 text=The user does not have permission to perform this action.
DBD::Sybase::db DESTROY failed: Server message number=262 severity=14 state=1 line=2 server=COMPENSA46 text=VIEW DATABASE STATE permission denied in database 'master'. Server message number=297 severity=16 state=1 line=2 server=COMPENSA46 text=The user does not have permission to perform this action. Server message number=3903 severity=16 state=1 line=2 server=COMPENSA46 text=The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. Server message number=3903 severity=16 state=1 line=2 server=COMPENSA46 text=The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.  during global destruction.

**Comment by lausser** [comment]
text=The user does not have permission to perform this action.
ext=VIEW DATABASE STATE permission denied in database 'master'.

Looks like you have not enough provileges.
Gerhard
